name: "schedule"
  
on:
  schedule:
    - cron: '0 10-18 * * *'
  
jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
      run: |
        curl -X GET "https://whatyoubendoing-iphone-plz.deno.dev?sms=1"